---
configuration_directory: "%{cwd}/spec/unit/infra/root"
state_file: "%{cwd}/state/root.tfstate"
vars:
  region: "%{hiera('region')}"
  availability_zones: "%{hiera('availability_zones')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"
